# -*- coding: utf-8 -*-
"""clase_15

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/125HsYv4Ud9KjJoietLmklMEovZnNQwzj
"""

import streamlit as st
import pandas as pd

# Title of the application
st.title('Aplicación de Análisis de Datos')

# Load the 'database_titanic.csv' file directly
# Replace 'path/to/database_titanic.csv' with the actual path to your file
df = pd.read_csv('database_titanic.csv')

# Display the first few rows of the DataFrame
st.write('Primeras 5 filas del archivo:')
st.write(df.head())